// This file is auto-generated by @hey-api/openapi-ts

export type GraphChangeNotificationV1 = {
  /**
   * MSA ID for which this notification is being sent
   */
  msaId: string;
  /**
   * Schema ID of graph that was updated
   */
  schemaId: number;
  /**
   * Page ID of graph page that was updated/deleted
   */
  pageId: number;
  /**
   * integer representation of the content hash of the updated page's previous state
   */
  prevContentHash: number;
  /**
   * integer representation of the content hash of the updated pages new state
   */
  currContentHash?: number;
  updateType: 'GraphPageUpdated' | 'GraphPageDeleted';
};

export enum updateType {
  GRAPH_PAGE_UPDATED = 'GraphPageUpdated',
  GRAPH_PAGE_DELETED = 'GraphPageDeleted',
}

export type GraphOperationStatusV1 = {
  /**
   * Job reference ID of a previously submitted graph update request
   */
  referenceId: string;
  status: 'pending' | 'expired' | 'failed' | 'succeeded';
};

export enum status {
  PENDING = 'pending',
  EXPIRED = 'expired',
  FAILED = 'failed',
  SUCCEEDED = 'succeeded',
}
