// This file is auto-generated by @hey-api/openapi-ts

export type ResetScannerDto = {
  /**
   * The block number to reset the scanner to
   */
  blockNumber?: number;
  /**
   * Number of blocks to rewind the scanner to (from `blockNumber` if supplied; else from latest block)
   */
  rewindOffset?: number;
  /**
   * Whether to schedule the new scan immediately or wait for the next scheduled interval
   */
  immediate?: boolean;
};

export type ChainWatchOptionsDto = {
  /**
   * Specific schema ids to watch for
   */
  schemaIds?: Array<number>;
  /**
   * Specific dsnpIds (msa_id) to watch for
   */
  dsnpIds?: Array<string>;
};

export type ContentSearchRequestDto = {
  /**
   * An optional client-supplied reference ID by which it can identify the result of this search
   */
  clientReferenceId?: string;
  /**
   * The block number to search (backward) from
   */
  startBlock?: number;
  /**
   * The number of blocks to scan (backwards)
   */
  blockCount: number;
  /**
   * The schemaIds/dsnpIds to filter by
   */
  filters?: ChainWatchOptionsDto;
  /**
   * A webhook URL to be notified of the results of this search
   */
  webhookUrl: string;
};

/**
 * Announcement types to send to the webhook
 */
export enum AnnouncementTypeName {
  TOMBSTONE = 'tombstone',
  BROADCAST = 'broadcast',
  REPLY = 'reply',
  REACTION = 'reaction',
  PROFILE = 'profile',
  UPDATE = 'update',
}

export type WebhookRegistrationDto = {
  /**
   * Webhook URL
   */
  url: string;
  announcementTypes: Array<AnnouncementTypeName>;
};
