# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Backend Verify PR
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
defaults:
  run:
    working-directory: "./backend"
jobs:
  test-start-sh:
    name: 'Common Tests'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: 'Bats start.sh Tests'
        run: |
          npm install -g bats
          npm run test:bats-start
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: backend/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
